modLoader="javafml"
loaderVersion="[${major_fml_version},)"
license="${license}"
issueTrackerURL="https://github.com/thomasglasser/${github_name}/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL = "https://api.modrinth.com/updates/${mod_id}/forge_updates.json?neoforge=include"
displayURL="https://github.com/thomasglasser/${github_name}/wiki"
logoFile="${icon}"
credits="${contributors}"
authors="${mod_author}"
description='''
${description}
'''
enumExtensions="META-INF/enum_extensions.json"
[[mixins]]
config = "${mod_id}.mixins.json"
[mc-publish]
loaders = ['neoforge']
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},${next_minecraft_version})"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="tommylib"
type="required"
versionRange="[${tommylib_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[${geckolib_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="smartbrainlib"
type="required"
versionRange="[${smartbrainlib_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="curios"
type="required"
versionRange="[${curios_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="trimmed"
type="required"
versionRange="[${trimmed_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="modonomicon"
type="optional"
versionRange="[${modonomicon_version},)"
ordering="NONE"
side="BOTH"